"""anchors corridors segments

Revision ID: 03d1eab73d5e
Revises: 
Create Date: 2026-04-29 00:02:24.691281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03d1eab73d5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'city', name='uq_anchors_name_city')
    )
    op.create_index('ix_anchors_city', 'anchors', ['city'], unique=False)
    op.create_table('corridors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_anchor_id', sa.UUID(), nullable=False),
    sa.Column('applicability_notes', sa.String(length=500), nullable=True),
    sa.Column('applicability_windows', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('contributor_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_corridors_status'),
    sa.ForeignKeyConstraint(['destination_anchor_id'], ['anchors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corridors_destination', 'corridors', ['destination_anchor_id'], unique=False)
    op.create_index('ix_corridors_status', 'corridors', ['status'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('corridor_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('from_anchor_id', sa.UUID(), nullable=False),
    sa.Column('to_anchor_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('instruction', sa.String(length=500), nullable=False),
    sa.Column('cost_ngn', sa.Integer(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('time_windows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('availability_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('taxi', 'keke', 'bike', 'walk', 'bus', 'car', 'mixed')", name='ck_segments_mode'),
    sa.CheckConstraint('from_anchor_id <> to_anchor_id', name='ck_segments_distinct_endpoints'),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_anchor_id'], ['anchors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_anchor_id'], ['anchors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corridor_id', 'sequence', name='uq_segments_corridor_sequence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segments')
    op.drop_index('ix_corridors_status', table_name='corridors')
    op.drop_index('ix_corridors_destination', table_name='corridors')
    op.drop_table('corridors')
    op.drop_index('ix_anchors_city', table_name='anchors')
    op.drop_table('anchors')
    # ### end Alembic commands ###
