"""add segment passthrough_anchor_ids

Revision ID: 21c02c28147c
Revises: 024050b6b283
Create Date: 2026-05-12 15:53:26.973618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21c02c28147c'
down_revision: Union[str, Sequence[str], None] = '024050b6b283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('passthrough_anchor_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'passthrough_anchor_ids')
    # ### end Alembic commands ###
