"""add transfer flag to segments

Revision ID: c4fa94f4d38c
Revises: 03d1eab73d5e
Create Date: 2026-04-30 18:13:30.515925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4fa94f4d38c'
down_revision: Union[str, Sequence[str], None] = '03d1eab73d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('transfer', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'transfer')
    # ### end Alembic commands ###
